import { TABLES } from '@acms/contracts';
import type { RecordMeta } from './generic-crud.module.js';

/** M1 学生生命周期域：7 张已注册飞书表，统一走 GenericCrudModule。 */
export const LIFECYCLE_METAS: RecordMeta[] = [
  {
    path: 'source-followups',
    tableId: TABLES.sourceFollowup.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['跟进编号'],
    statusField: '闭环状态',
    defaultStatus: '待处理',
    searchField: '跟进内容',
    dateFields: ['活动参与日期', '跟进日期', '下次跟进日期'],
    sortField: '跟进日期',
  },
  {
    path: 'student-attendances',
    tableId: TABLES.attendance.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['考勤编号'],
    statusField: '考勤状态',
    defaultStatus: '正常',
    searchField: '班级',
    dateFields: ['考勤日期', '到校时间', '离校时间'],
    sortField: '考勤日期',
  },
  {
    path: 'grades',
    tableId: TABLES.academicGrade.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['成绩编号'],
    numbers: ['成绩', '满分'],
    statusField: '成绩状态',
    defaultStatus: '草稿',
    searchField: '课程',
    dateFields: ['考核日期'],
    sortField: '考核日期',
  },
  {
    path: 'practice-activities',
    tableId: TABLES.practiceActivity.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['活动编号'],
    numbers: ['服务或参与时长'],
    statusField: '安全确认状态',
    defaultStatus: '待确认',
    searchField: '活动名称',
    dateFields: ['活动开始日期', '活动结束日期'],
    sortField: '活动开始日期',
  },
  {
    path: 'home-school-comms',
    tableId: TABLES.homeSchoolComm.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['沟通编号'],
    statusField: '闭环状态',
    defaultStatus: '无需跟进',
    searchField: '沟通内容',
    dateFields: ['沟通时间', '跟进截止日期', '闭环日期'],
    sortField: '沟通时间',
  },
  {
    path: 'stage-evaluations',
    tableId: TABLES.stageEvaluation.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['评价编号'],
    statusField: '评价完整度',
    defaultStatus: '待提交',
    searchField: '评价内容',
    dateFields: ['评价日期', '复核日期'],
    sortField: '评价日期',
  },
  {
    path: 'alumni-followups',
    tableId: TABLES.alumniFollowup.tableId,
    readPerm: 'student:read',
    writePerm: 'student:write',
    readonly: ['跟进编号'],
    statusField: '跟进状态',
    defaultStatus: '待跟进',
    searchField: '跟进事项',
    dateFields: ['跟进时间', '下次跟进日期'],
    sortField: '跟进时间',
  },
];
